name: Build adocs and deploy skos-ap-no to Github Pages

on:
  push:
    branches:
      - main
    paths:
      - skos-ap-no/**
  workflow_dispatch:

jobs:
  adoc_build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: asciidoctor build
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build html
      id: adocbuild_html
      uses: tonynv/asciidoctor-action@master
      with:
          program: "asciidoctor -D skos-ap-no -o index.html -a lang=en skos-ap-no/main.adoc"

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: skos-ap-no
        destination_dir: ./skos-ap-no
        keep_files: true
